name: CI
on: push
jobs:
  ci:
    name: Build + Test
    runs-on: ubuntu-latest
    steps:

    - name: Check out source code
      uses: actions/checkout@v3.1.0

    - name: Set up Go 1.18
      uses: actions/setup-go@v3.3.1
      with:
        go-version: 1.18

    - name: Build
      run: go build ./bind ./expect ./golden ./json ./mt

    - name: Test
      run: go test -cover ./bind ./expect ./golden ./json ./mt
