name: CI
on: push
jobs:
  ci:
    name: Build + Test
    runs-on: ubuntu-latest
    steps:

    - name: Check out source code
      uses: actions/checkout@v2.4.0

    - name: Set up Go 1.17
      uses: actions/setup-go@v2.1.4 
      with:
        go-version: 1.17

    - name: Build
      run: go build ./mt ./golden

    - name: Test
      run: go test -cover ./mt ./golden
