name: CI
on:
  push:
    branches:
      - main
jobs:
  ci:
    name: Build + Test
    runs-on: ubuntu-latest
    steps:

    - name: Check out source code
      uses: actions/checkout@v2.4.0

    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go

    - name: Build
      run: go build ./mt ./golden ./examples

    - name: Test
      run: go test ./mt ./golden ./examples
